//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualATM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int AccountId { get; set; }
        public int TransactionId { get; set; }
        public string TransactionType { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public int Amount { get; set; }
        public string TransactionDescription { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
